# this configuration is only used for forked PRs
version: 2.1

jobs:
  build:
    docker:
      - image: cumuluss/circleci:node-8.11
      - name: localstack
        image: localstack/localstack:0.8.6
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: core installation
          command: |
            if [ -z "${CIRCLE_PR_REPONAME}" ]; then
              echo 'skipping the step because this is not a forked PR'
            else
              yarn
            fi

      - run:
          name: Installing Dependencies
          command: |
            if [ -z "${CIRCLE_PR_REPONAME}" ]; then
              echo 'skipping the step because this is not a forked PR'
            else
              sudo mkdir -p /home/user/
              sudo cp -r packages/test-data/keys /home/user/.ssh

              # start ftp
              sudo rm -rf /home/vsftpd
              sudo ln -s /home/circleci/project/packages/test-data /home/vsftpd
              sudo service vsftpd start || true

              # start http service
              sudo rm -rf /var/www/html
              sudo ln -s /home/circleci/project/packages/test-data /var/www/html
              sudo service apache2 start

              # start sftp service
              sudo bash /usr/sbin/sftp.sh user:password
              sudo cp -r /home/circleci/project/packages/test-data/* /home/user/

              yarn bootstrap-no-build
            fi

      - run:
          name: Running Tests
          environment:
            LOCALSTACK_HOST: localstack
          command: |
            if [ -z "${CIRCLE_PR_REPONAME}" ]; then
              echo 'skipping the step because this is not a forked PR'
            else
              ./node_modules/.bin/lerna run test --ignore @cumulus/api --concurrency 1
              cd packages/api
              ./node_modules/.bin/ava --serial
              cd ../..
            fi
