default:
  prefix: test-cumulus-integration
  stackName: '{{prefix}}-iam'
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM

  system_bucket: '{{buckets.internal.name}}'

  useNgapPermissionBoundary: false

  buckets:
    internal:
      name: change-me
      type: internal
    private:
      name: change-me
      type: private
    protected:
      name: change-me
      type: protected
    public:
      name: change-me
      type: public
  params:
     - name: ResourcePrefix
       value: '{{prefix}}'
